package cn.edu.hbuas.sl.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.edu.hbuas.sl.bean.AllGoods;
import cn.edu.hbuas.sl.bean.MyLost;
import cn.edu.hbuas.sl.bean.MySeek;
import cn.edu.hbuas.sl.bean.User;
import cn.edu.hbuas.sl.bean.Feedback;

import cn.edu.hbuas.sl.bean.AllGoodsDao;
import cn.edu.hbuas.sl.bean.MyLostDao;
import cn.edu.hbuas.sl.bean.MySeekDao;
import cn.edu.hbuas.sl.bean.UserDao;
import cn.edu.hbuas.sl.bean.FeedbackDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig allGoodsDaoConfig;
    private final DaoConfig myLostDaoConfig;
    private final DaoConfig mySeekDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig feedbackDaoConfig;

    private final AllGoodsDao allGoodsDao;
    private final MyLostDao myLostDao;
    private final MySeekDao mySeekDao;
    private final UserDao userDao;
    private final FeedbackDao feedbackDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        allGoodsDaoConfig = daoConfigMap.get(AllGoodsDao.class).clone();
        allGoodsDaoConfig.initIdentityScope(type);

        myLostDaoConfig = daoConfigMap.get(MyLostDao.class).clone();
        myLostDaoConfig.initIdentityScope(type);

        mySeekDaoConfig = daoConfigMap.get(MySeekDao.class).clone();
        mySeekDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        feedbackDaoConfig = daoConfigMap.get(FeedbackDao.class).clone();
        feedbackDaoConfig.initIdentityScope(type);

        allGoodsDao = new AllGoodsDao(allGoodsDaoConfig, this);
        myLostDao = new MyLostDao(myLostDaoConfig, this);
        mySeekDao = new MySeekDao(mySeekDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        feedbackDao = new FeedbackDao(feedbackDaoConfig, this);

        registerDao(AllGoods.class, allGoodsDao);
        registerDao(MyLost.class, myLostDao);
        registerDao(MySeek.class, mySeekDao);
        registerDao(User.class, userDao);
        registerDao(Feedback.class, feedbackDao);
    }
    
    public void clear() {
        allGoodsDaoConfig.clearIdentityScope();
        myLostDaoConfig.clearIdentityScope();
        mySeekDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        feedbackDaoConfig.clearIdentityScope();
    }

    public AllGoodsDao getAllGoodsDao() {
        return allGoodsDao;
    }

    public MyLostDao getMyLostDao() {
        return myLostDao;
    }

    public MySeekDao getMySeekDao() {
        return mySeekDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public FeedbackDao getFeedbackDao() {
        return feedbackDao;
    }

}
