package cn.edu.hbuas.sl.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MY_LOST".
*/
public class MyLostDao extends AbstractDao<MyLost, Long> {

    public static final String TABLENAME = "MY_LOST";

    /**
     * Properties of entity MyLost.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Number = new Property(0, Long.class, "number", true, "_id");
        public final static Property Telphone = new Property(1, String.class, "telphone", false, "TELPHONE");
        public final static Property Goods = new Property(2, String.class, "goods", false, "GOODS");
        public final static Property Description = new Property(3, String.class, "description", false, "DESCRIPTION");
        public final static Property LostTime = new Property(4, String.class, "lostTime", false, "LOST_TIME");
        public final static Property LostArea = new Property(5, String.class, "lostArea", false, "LOST_AREA");
        public final static Property Address = new Property(6, String.class, "address", false, "ADDRESS");
        public final static Property Contacts = new Property(7, String.class, "contacts", false, "CONTACTS");
        public final static Property ContactsTel = new Property(8, String.class, "contactsTel", false, "CONTACTS_TEL");
        public final static Property Pic1 = new Property(9, String.class, "pic1", false, "PIC1");
        public final static Property Pic2 = new Property(10, String.class, "pic2", false, "PIC2");
        public final static Property Pic3 = new Property(11, String.class, "pic3", false, "PIC3");
        public final static Property Pic4 = new Property(12, String.class, "pic4", false, "PIC4");
    }


    public MyLostDao(DaoConfig config) {
        super(config);
    }
    
    public MyLostDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MY_LOST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: number
                "\"TELPHONE\" TEXT NOT NULL ," + // 1: telphone
                "\"GOODS\" TEXT NOT NULL ," + // 2: goods
                "\"DESCRIPTION\" TEXT," + // 3: description
                "\"LOST_TIME\" TEXT NOT NULL ," + // 4: lostTime
                "\"LOST_AREA\" TEXT NOT NULL ," + // 5: lostArea
                "\"ADDRESS\" TEXT NOT NULL ," + // 6: address
                "\"CONTACTS\" TEXT NOT NULL ," + // 7: contacts
                "\"CONTACTS_TEL\" TEXT NOT NULL ," + // 8: contactsTel
                "\"PIC1\" TEXT," + // 9: pic1
                "\"PIC2\" TEXT," + // 10: pic2
                "\"PIC3\" TEXT," + // 11: pic3
                "\"PIC4\" TEXT);"); // 12: pic4
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MY_LOST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MyLost entity) {
        stmt.clearBindings();
 
        Long number = entity.getNumber();
        if (number != null) {
            stmt.bindLong(1, number);
        }
        stmt.bindString(2, entity.getTelphone());
        stmt.bindString(3, entity.getGoods());
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(4, description);
        }
        stmt.bindString(5, entity.getLostTime());
        stmt.bindString(6, entity.getLostArea());
        stmt.bindString(7, entity.getAddress());
        stmt.bindString(8, entity.getContacts());
        stmt.bindString(9, entity.getContactsTel());
 
        String pic1 = entity.getPic1();
        if (pic1 != null) {
            stmt.bindString(10, pic1);
        }
 
        String pic2 = entity.getPic2();
        if (pic2 != null) {
            stmt.bindString(11, pic2);
        }
 
        String pic3 = entity.getPic3();
        if (pic3 != null) {
            stmt.bindString(12, pic3);
        }
 
        String pic4 = entity.getPic4();
        if (pic4 != null) {
            stmt.bindString(13, pic4);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MyLost entity) {
        stmt.clearBindings();
 
        Long number = entity.getNumber();
        if (number != null) {
            stmt.bindLong(1, number);
        }
        stmt.bindString(2, entity.getTelphone());
        stmt.bindString(3, entity.getGoods());
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(4, description);
        }
        stmt.bindString(5, entity.getLostTime());
        stmt.bindString(6, entity.getLostArea());
        stmt.bindString(7, entity.getAddress());
        stmt.bindString(8, entity.getContacts());
        stmt.bindString(9, entity.getContactsTel());
 
        String pic1 = entity.getPic1();
        if (pic1 != null) {
            stmt.bindString(10, pic1);
        }
 
        String pic2 = entity.getPic2();
        if (pic2 != null) {
            stmt.bindString(11, pic2);
        }
 
        String pic3 = entity.getPic3();
        if (pic3 != null) {
            stmt.bindString(12, pic3);
        }
 
        String pic4 = entity.getPic4();
        if (pic4 != null) {
            stmt.bindString(13, pic4);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MyLost readEntity(Cursor cursor, int offset) {
        MyLost entity = new MyLost( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // number
            cursor.getString(offset + 1), // telphone
            cursor.getString(offset + 2), // goods
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // description
            cursor.getString(offset + 4), // lostTime
            cursor.getString(offset + 5), // lostArea
            cursor.getString(offset + 6), // address
            cursor.getString(offset + 7), // contacts
            cursor.getString(offset + 8), // contactsTel
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // pic1
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // pic2
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // pic3
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // pic4
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MyLost entity, int offset) {
        entity.setNumber(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTelphone(cursor.getString(offset + 1));
        entity.setGoods(cursor.getString(offset + 2));
        entity.setDescription(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLostTime(cursor.getString(offset + 4));
        entity.setLostArea(cursor.getString(offset + 5));
        entity.setAddress(cursor.getString(offset + 6));
        entity.setContacts(cursor.getString(offset + 7));
        entity.setContactsTel(cursor.getString(offset + 8));
        entity.setPic1(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setPic2(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setPic3(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setPic4(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MyLost entity, long rowId) {
        entity.setNumber(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MyLost entity) {
        if(entity != null) {
            return entity.getNumber();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MyLost entity) {
        return entity.getNumber() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
